# URL
baseurl: "/strassenraumkarte-tarp"
url: "https://mtrnord.github.io"

# Content
# Also used for Social Sharing https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
locale: de_DE
title: Straßenraumkarte Tarp
description: Spezialkarten für Tarp zum Straßenraum und zur Parkplatzdichte.
author: Alex Seidel
logo: /images/openstreetmap-osm-logo.png
image:
  path: /images/social-sharing.png
  alt: Ausschnitt der Parkraumkarte Tarp mit Visualisierung des Flächenverbrauchs.
twitter:
  username: "@osmberlin"
  card: summary_large_image

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# email: your-email@example.com
# github_username:  SupaplexOSM

# Build settings

permalink: /posts/:year-:month-:day-:title

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3
  parse_block_html: true

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# We do not want the TailwindCSS Source File to be looked at by Jekyll
exclude: ["css-src"]
